version: '3.1'

services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: super-secret-pass
            MYSQL_USER: nodejs
            MYSQL_PASSWORD: nodejspassword
            MYSQL_DATABASE: users
        ports:
            - "3306:3306"
    nginx:
        image: nginx:latest
        restart: always

    automatic_fabric:
        image: node:12.18
        restart: always
        entrypoint:
            - npm
            - run
            - start
