version: '2.0'
services:
  mariadb:
    image: mariadb:10.5.4
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./db:/data"
    environment:
      MYSQL_USER: "nodejs"
      MYSQL_PASSWORD: "nodejspassword"
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    
